Persistence Layer and Module binding
SnickerdoodleLabs/crunchDB pull request #2
Opened 2024-04-17 15:26 UTC by dlgn2

2024-04-23 18:59 UTC, sdmuki requested changes

2024-04-23 18:59 UTC, sdmuki commented on src/implementations/CrunchDB.ts
> +import { ICrunchDB } from 'crunchDB/interfaces/ICrunchDB';
import { ICrunchDB } from 'crunchDB/interfaces';
# use module imports from sibling directories

2024-04-23 18:59 UTC, sdmuki commented on src/implementations/business/volatile/IPersistenceConfigProvider.ts
> +import { IPersistenceConfig } from 'crunchDB/implementations/business/volatile/IPersistenceConfig.js';
no js imports.

2024-04-23 18:59 UTC, sdmuki commented on src/implementations/business/volatile/IVolatileStorage.ts
> +import { IVolatileCursor } from 'crunchDB/implementations/business/volatile/IVolatileCursor.js';
no js imports

2024-04-23 18:59 UTC, sdmuki commented on src/implementations/business/volatile/IndexedDB.ts
> +import { IndexedDBCursor } from 'crunchDB/implementations/business/volatile/IndexedDBCursor.js';
no js imports

2024-04-23 18:59 UTC, sdmuki commented on src/implementations/business/volatile/VolatileTableIndex.ts
> +import { IStorageIndex } from 'crunchDB/implementations/business/volatile/IStorageIndex.js';
js imports

2024-04-23 18:59 UTC, sdmuki commented on src/objects/business/VolatileDataUpdate.ts
> +import { VersionedObject } from "@objects/businessObjects/versioned/index.js";
js imports not needed. use "objects". get rid of the @. We will use @ for domains only which is not decided yet

2024-04-23 18:59 UTC, sdmuki commented on src/objects/business/VolatileDataUpdate.ts
> +import { EDataUpdateOpCode } from "@objects/enum/index.js";
objects/enum

2024-04-23 18:59 UTC, sdmuki commented on src/objects/business/VolatileDataUpdate.ts
> +} from "@objects/primitives/index.js";
objects/primitives

2024-04-30 16:06 UTC, SnickerChar reviewed
There's a lot of stuff you are bringing in that is irrelevant to CrunchDB. It's not going to be doing backups or versioning, for instance.

2024-04-30 16:06 UTC, SnickerChar commented on package-lock.json
package-lock.json implies using NPM, you should probably be using Yarn

2024-04-30 16:06 UTC, SnickerChar commented on src/interfaces/utilities/ILogUtils.ts
> +  getPino(): pino.Logger;
You can remove this method for sure. It's been a carry-forward for way too long.

2024-04-30 16:06 UTC, SnickerChar commented on src/implementations/business/volatile/VolatileStorageSchemaProvider.ts
> +import {
The storage schema for the DB needs to be provided via the CrunchDB constructor; it's not something that will be configured or known before you initialize the CrunchDB

2024-04-30 16:06 UTC, SnickerChar commented on src/objects/business/VersionedObject.ts
> +import { PropertiesOf } from 'crunchDB/objects/utilities';
VersionedObject is not something that CrunchDB should worry about. It should be provided with the current schema on initialization.

2024-04-30 16:06 UTC, SnickerChar commented on src/objects/business/VolatileDataUpdate.ts
> +
CrunchDB shouldn't be updating the DB

2024-04-30 16:06 UTC, SnickerChar commented on src/objects/enum/EBackupPriority.ts
> +export enum EBackupPriority {
All the things related to backups should be nuked.

2024-05-06 16:08 UTC, closed without merging